#!/usr/bin/env php
<?php
/**
 * Shell wrapper for php_testability
 * @author Edson Medina <edsonmedina@gmail.com>
 */

// turn off html errors
ini_set('html_errors', 'off');

// load autoloader
$autoloader_locations = array (
	__DIR__.'/../../autoload.php', 
	__DIR__.'/vendor/autoload.php', 
	__DIR__.'/../../../vendor/autoload.php'
);
foreach ($autoloader_locations as $file) {
    if (file_exists($file)) {
    	require_once $file;
    }
}

use Commando\Command;

// parse CLI arguments
$cmd = new Command();
$cmd->setHelp ('php_availability by Edson Medina');
$cmd->option()->require()->referToAs('path')->describeAs('A file or a directory to analyse')->file()->default(__DIR__);
$cmd->option('output')->require()->alias('o')->describeAs('Path for writing the report');

// run
define ('PATH', $cmd[0]);
require __DIR__.'/testability.php';
