#!/usr/bin/env php
<?php
/**
 * Shell wrapper for php_testability
 * @author Edson Medina <edsonmedina@gmail.com>
 */

// turn off html errors
ini_set('html_errors', 'off');
ini_set('memory_limit', '1G');
error_reporting (E_ALL); // that's how we roll

// load autoloader
$autoloader_locations = array (
	__DIR__.'/../../../autoload.php', // from installed bin or src dir
	__DIR__.'/../vendor/autoload.php' // from dev version
);
$loaded = false;
foreach ($autoloader_locations as $file) 
{
    if (file_exists($file)) 
    {
    	require_once $file;
    	$loaded = true;
    	break;
    }
}
if (!$loaded) {
	die ("Can't find autoloader ".__DIR__."\n");
}

// parse CLI arguments
$cmd = new Commando\Command();
$cmd->setHelp ('php_testability by Edson Medina');
// TODO check if file exists
$cmd->option()->require()->referToAs('path')->describeAs('A file or a directory to analyse')->default(__DIR__); 
$cmd->option('output')->alias('o')->describeAs('Path for writing the report')->default(__DIR__.'/report');
$cmd->option('exclude')->alias('x')->describeAs('Exclude directories');
$cmd->option('debug')->alias('g')->describeAs('Output debugging information (and debug.log)')->boolean();

// run
define ('PATH', rtrim($cmd[0], DIRECTORY_SEPARATOR));

if (!file_exists(PATH)) {
	die ("\nInvalid path:\n".PATH."\n\n");
}

define ('EXCLUDE_DIRS', preg_replace('/\s*,\s*/',',',$cmd['exclude'])); // trim values
define ('REPORT_DIR', $cmd['output']);
define ('DEBUG', $cmd['debug']);

edsonmedina\php_testability\Testability::runReport();
